package com.ironhack.edgeservice.model.entities.security;

import com.ironhack.edgeservice.model.enums.Role;

import java.util.Objects;

/**
 * User model
 */
public class UserSecurity {
    /**
     * Long id autogenerated
     */
    private Long id;
    /**
     * String username
     */
    private String username;
    /**
     * String password
     */
    private String password;
    /**
     * Enum Role rol
     */
    private Role rol;

    /**
     * Default constructor
     */
    public UserSecurity() {
    }

    /**
     * Custom constructor
     * @param username String username
     * @param password String password
     * @param rol Role rol
     */
    public UserSecurity(String username, String password, Role rol) {
        this.username = username;
        this.password = password;
        this.rol = rol;
    }

    /**
     * Get id
     * @return Long id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set id
     * @param id Long id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get username
     * @return String username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set username
     * @param username String username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get password
     * @return String password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set password
     * @param password String password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get rol
     * @return Role rol
     */
    public Role getRol() {
        return rol;
    }

    /**
     * Set rol
     * @param rol Role rol
     */
    public void setRol(Role rol) {
        this.rol = rol;
    }

    /**
     * Compare two Users
     * @param o User o
     * @return Are equals
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        UserSecurity user = (UserSecurity) o;
        return Objects.equals(username, user.username) &&
                rol == user.rol;
    }

    /**
     * HashCode
     * @return int hashCode
     */
    @Override
    public int hashCode() {
        return Objects.hash(username, rol);
    }
}