package com.ironhack.securityservice.model;

import com.ironhack.securityservice.enums.Role;
import com.sun.istack.NotNull;

import javax.persistence.*;
import java.util.Objects;

/**
 * User model
 */
@Entity
public class User {
    /**
     * Long id autogenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * String username
     */
    @NotNull
    private String username;
    /**
     * String password
     */
    @NotNull
    private String password;
    /**
     * Enum Role rol
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    private Role rol;

    /**
     * Default constructor
     */
    public User() {
    }

    /**
     * Custom constructor
     * @param username String username
     * @param password String password
     * @param rol Role rol
     */
    public User(@NotNull String username, @NotNull String password, Role rol) {
        this.username = username;
        this.password = password;
        this.rol = rol;
    }

    /**
     * Get id
     * @return Long id
     */
    public Long getId() {
        return id;
    }

    /**
     * Set id
     * @param id Long id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get username
     * @return String username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set username
     * @param username String username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get password
     * @return String password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set password
     * @param password String password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Get rol
     * @return Role rol
     */
    public Role getRol() {
        return rol;
    }

    /**
     * Set rol
     * @param rol Role rol
     */
    public void setRol(Role rol) {
        this.rol = rol;
    }

    /**
     * Compare two Users
     * @param o User o
     * @return Are equals
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(username, user.username) &&
                rol == user.rol;
    }

    /**
     * HashCode
     * @return int hashCode
     */
    @Override
    public int hashCode() {
        return Objects.hash(username, rol);
    }
}